# Generated by Django 3.2.13 on 2022-05-25 10:01

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_post_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='preview',
            field=models.ImageField(blank=True, upload_to=news.models.directory_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='profile', to='news.Post'),
        ),
    ]
